### ISSUE TITLE
White tab for active tab

### ISSUE THREAD

**Issue by SeanJM** [joshglendenning/darkular-syntax#1]
Hi, I find the white background for the active tab to be quite distracting during coding.

Thank you for porting this theme.

**Comment by isobit** [comment]
Not sure if I can fix that since it's up to the UI theme to color the tabs. I agree, though, the white looks bad with the One Dark UI theme. You could always just fix it in your stylesheet (Atom Menu->Open your stylesheet).

This is what I did in mine: 

```
.tab-bar .tab{
  border-radius: 0;
  border-image: none !important;
  border-left: 1px solid #222;
  &.active {
    &::after {
      border-top: 1px solid #555;
    }
  }
  &::before {
    display: none;
  }
  &::after {
    border-bottom: none;
    background: none !important;
    border-image: none;
  }
}
```

The only real important bit is the `background: none !important;` in the after section, everything else is just tweaking.
